<!doctype html>
<html>
 <body>
 <head>
  <title>How to install Mimo!</title>
 </head>
 <h1>How to install Mimo!</h1>
<h3><strong>Steps:</strong></h3>
  <ol>
  <li>Go to Play Store </li>
  <li>Search Mimo: Learn To Code</li>
  <li>Then click Install!</li>
  <li><strong>Must</strong> Have Google Account!</li>
<img src="https://dribbble.com/shots/4631333-Mimo-App-Icon" width="200" height="200">


  </ol>
 </body>
</html>
